// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuCa-gU0LzcehC8mfkru7ELU3P2CgrH3U',
    appId: '1:1092541913977:web:561e0a929631dd5481ada8',
    messagingSenderId: '1092541913977',
    projectId: 'advmobprog-firebase-57ea3',
    authDomain: 'advmobprog-firebase-57ea3.firebaseapp.com',
    storageBucket: 'advmobprog-firebase-57ea3.firebasestorage.app',
    measurementId: 'G-5JDHN00W4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC719DOteFcOETyySXDRA3KQxQMdt5MfcM',
    appId: '1:1092541913977:android:12ac41fff9b0094981ada8',
    messagingSenderId: '1092541913977',
    projectId: 'advmobprog-firebase-57ea3',
    storageBucket: 'advmobprog-firebase-57ea3.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBup0F54kyceYvg-tPSYHt69lUMWhgEB98',
    appId: '1:1092541913977:ios:9ca50efd09d77d1f81ada8',
    messagingSenderId: '1092541913977',
    projectId: 'advmobprog-firebase-57ea3',
    storageBucket: 'advmobprog-firebase-57ea3.firebasestorage.app',
    iosBundleId: 'com.example.abonitaAdvmobprog',
  );
}
